#!/bin/sh
# $Id: pdf2eps,v 0.01 2005/10/28 00:55:46 Herbert Voss Exp $
# Convert PDF to encapsulated PostScript.
# usage:
# pdf2eps <page number> <pdf file without ext>
#
# based on the: http://tex.stackexchange.com/questions/20883/how-to-convert-pdf-to-eps
#
# Use-case: 
#	-get pdf (e.g. exported from Nengo), crop it in preview 
#	-call pdf2eps 1 source.pdf
#	-use eps in LaTeX

pdfcrop "$2" "$2-temp.pdf"
pdftops -f $1 -l $1 -eps "$2-temp.pdf" "$2.eps"
rm  "$2-temp.pdf"